name       : perl-exception-class
version    : 1.39
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Exception-Class-1.39.tar.gz : 819c756a69a6d1e31f396eca6a508b07b0a522a035b904cd1d432353cc362083
license    :
    - Artistic-1.0-Perl
    - GPL-1.0
summary    : Perl Exception Class Module
description: |
    A module that allows you to declare real exception classes in Perl
patterns   :
    - /usr/share/man/man3/*
setup      : |
    perl Makefile.PL PREFIX=/usr INSTALLDIRS=vendor DESTDIR=%installroot%
build      : |
    %make
install    : |
    %make_install
    rm %installroot%/usr/lib/perl5/5.20.1/x86_64-linux/perllocal.pod
