name       : perl-exception-class
version    : '1.45'
release    : 13
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Exception-Class-1.45.tar.gz : 5482a77ef027ca1f9f39e1f48c558356e954936fc8fbbdee6c811c512701b249
license    :
    - Artistic-1.0-Perl
    - GPL-1.0-or-later
summary    : Perl Exception Class Module
component  : programming.perl
description: |
    A module that allows you to declare real exception classes in Perl
patterns   :
    - /usr/share/man/man3/*
builddeps  :
    - perl-class-data-inheritable
    - perl-devel-stacktrace
rundeps    :
    - perl-class-data-inheritable
    - perl-devel-stacktrace
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
