name       : perl-exception-class
version    : 1.44
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Exception-Class-1.44.tar.gz : 33f3fbf8b138d3b04ea4ec0ba83fb0df6ba898806bcf4ef393d4cafc1a23ee0d
license    :
    - Artistic-1.0-Perl
    - GPL-1.0
summary    : Perl Exception Class Module
component  : programming.perl
description: |
    A module that allows you to declare real exception classes in Perl
patterns   :
    - /usr/share/man/man3/*
builddeps  :
    - perl-class-data-inheritable
    - perl-devel-stacktrace
rundeps    :
    - perl-class-data-inheritable
    - perl-devel-stacktrace
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
