name       : perl-exception-class
version    : '1.42'
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Exception-Class-1.42.tar.gz : 8bb4ee64d3770d6812bda36890ef5df418573287eb8eccbb106f04c981dea22b
license    :
    - Artistic-1.0-Perl
    - GPL-1.0
summary    : Perl Exception Class Module
component  : programming.perl
description: |
    A module that allows you to declare real exception classes in Perl
patterns   :
    - /usr/share/man/man3/*
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
